# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45b35becdf744308d9fcba2f25dfd0305eb6c51b25139a2526ad038c59a6dc6d7c07519ba9faa550b383d357c265d87e429762abf5addc4c14b773080fbc1a8b

test:
  secret_key_base: 62a16389801626501484d02226dbb29b5ccd2542d50c041f7f3dd20755affaf96cda4f41c3040735b99f24adb6631efe8886d52133e100a61275b30692566807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
